#!/usr/bin/env python

NONE=		"\033[0m"
BOLD=		"\033[1m"
HALFBRIGHT=	"\033[2m"
UNDERSCORE=	"\033[4m"
BLINK=		"\033[5m"
REVERSE=	"\033[7m"

#/****************************COLORS***************************************/
C_BLACK=	"\033[30m"
C_RED=		"\033[31m"
C_GREEN=	"\033[32m"
C_YELLOW=	"\033[33m"
C_BLUE=		"\033[34m"
C_MAGENTA=	"\033[35m"
C_CYAN=		"\033[36m"
C_GRAY=		"\033[37m"

#/**************************BACKGROUNDS************************************/
BG_BLACK=	"\033[40m"
BG_RED=		"\033[41m"
BG_GREEN=	"\033[42m"
BG_YELLOW=	"\033[43m"
BG_BLUE=	"\033[44m"
BG_MAGENTA=	"\033[45m"
BG_CYAN=	"\033[46m"
BG_GRAY=	"\033[47m"

list_style = {
	'none':'0',
	'bold':'1',
	'halfbright':'2',
	'underscore':'4',
	'blink':'5',
	'reverse':'7',
	'black':'30',
	'red':'31',
	'green':'32',
	'yellow':'33',
	'blue':'34',
	'magenta':'35',
	'cyan':'36',
	'gray':'37',
	'bblack':'40',
	'bred':'41',
	'bgreen':'42',
	'byellow':'43',
	'bblue':'44',
	'bmagenta':'45',
	'bcyan':'46',
	'gray':'47'
}

import sys
import os
from ctypes import cdll
from ctypes import *

lib = cdll.LoadLibrary("write-inline.so")
cprint = lib.print_inline

for x in sys.argv:
	if x != sys.argv[0]:
		try:
			s = "\033["+list_style[x]+"m"
			cprint(s)
		except:
			print "color <stylo | font_color | background>"
			print "usage:"
			for y in list_style:
				print "\t%s" %(y)

			sys.exit()
